# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

# azure-pipeline.yml

trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'docker_connection'  # Specify your Docker Hub service connection
    repository: 'yourdockerhubusername/mysql'  # Path to your MySQL Dockerfile
    command: 'build'

- task: Docker@2
  inputs:
    containerRegistry: 'docker_connection'
    repository: 'maoravidan/projectapp/react'
    command: 'build'
    Dockerfile: '$(Build.SourcesDirectory)/test1/Dockerfile'

- task: Docker@2
  inputs:
    containerRegistry: 'docker_connection'
    repository: 'maoravidan/projectapp/fast_api'
    command: 'build'
    Dockerfile: '$(Build.SourcesDirectory)/fast_api/Dockerfile'

- task: Docker@2
  inputs:
    containerRegistry: 'docker_connection'
    repository: 'maoravidan/projectapp/mysql'
    command: 'push'

- task: Docker@2
  inputs:
    containerRegistry: 'docker_connection'
    repository: 'maoravidan/projectapp/react'
    command: 'push'

- task: Docker@2
  inputs:
    containerRegistry: 'docker_connection'
    repository: 'maoravidan/projectapp/fast_api'
    command: 'push'
