trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: BuildAndPushDockerImages
  displayName: 'Build and push Docker images'
  steps:
  - task: Docker@2
    displayName: 'Build MySQL Docker image'
    inputs:
      containerRegistry: 'docker_connection'
      repository: 'maoravidan/projectapp/mysql'
      command: 'build'

  - task: Docker@2
    displayName: 'Build React Docker image'
    inputs:
      containerRegistry: 'docker_connection'
      repository: 'maoravidan/projectapp/react'
      command: 'build'
      Dockerfile: '$(Build.SourcesDirectory)/test1/Dockerfile'

  - task: Docker@2
    displayName: 'Build FastAPI Docker image'
    inputs:
      containerRegistry: 'docker_connection'
      repository: 'maoravidan/projectapp/fast_api'
      command: 'build'
      Dockerfile: '$(Build.SourcesDirectory)/fast_api/Dockerfile'

  - task: Docker@2
    displayName: 'Push MySQL Docker image'
    inputs:
      containerRegistry: 'docker_connection'
      repository: 'maoravidan/projectapp/mysql'
      command: 'push'

  - task: Docker@2
    displayName: 'Push React Docker image'
    inputs:
      containerRegistry: 'docker_connection'
      repository: 'maoravidan/projectapp/react'
      command: 'push'

  - task: Docker@2
    displayName: 'Push FastAPI Docker image'
    inputs:
      containerRegistry: 'docker_connection'
      repository: 'maoravidan/projectapp/fast_api'
      command: 'push'
