trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: BuildAndPushDockerImage
  displayName: 'Build and push Docker image'
  steps:
  - task: Docker@2
    displayName: 'Build and push Docker image'
    inputs:
      containerRegistry: 'docker_connection' # Replace 'docker_connection' with your Docker service connection name
      repository: 'your_repository_name' # Replace 'your_repository_name' with your Docker repository name
      command: 'buildAndPush'
      Dockerfile: '**/Dockerfile'
      tags: '$(Build.BuildId)'
